dist: xenial
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy3"
install:
 - pip install --upgrade pip
 - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install pylzma; fi"
 - "pip install -r 'requirements.txt' -r 'requirements-build.txt'"
before_script:
 - pylint src/main/python/fast_pyspark_tester
script:
 - pyb -X
after_success:
 - bash <(curl -s https://codecov.io/bash)
