dist: xenial
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy3"
install:
 - pip install --upgrade pip
 - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install pylzma; fi"
 - "pip install -r 'requirements.txt' -r 'requirements-build.txt'"
script:
 - pyb -X
after_success:
 - bash <(curl -s https://gist.githubusercontent.com/svaningelgem/b748f492a3bee734e511b0de685ea399/raw/dedc37f346e97848e5a720254640fbc3cded827b/codecov_bash) -v
