name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.6
          - os: ubuntu-latest
            python: 3.7
          - os: ubuntu-latest
            python: 3.8
          - os: ubuntu-latest
            python: 3.9

          - os: macos-latest
            python: 3.6
          - os: macos-latest
            python: 3.7
          - os: macos-latest
            python: 3.8
          - os: macos-latest
            python: 3.9

          - os: windows-latest
            python: 3.6
          - os: windows-latest
            python: 3.7
          - os: windows-latest
            python: 3.8
          - os: windows-latest
            python: 3.9

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[tests,scripts,sql]" --use-deprecated=legacy-resolver
    - name: Print environment
      run: |
        python -m pip freeze
        python --version
        python -c "import build; print(f'Current version: {build.version}')"
    - name: flake8
      run: flake8 src
    - name: Lint
      run: pylint src --disable=fixme
    - name: pycodestyle
      run: python -m src
    - name: Test All
      run: python -m pytest -vv
